name: Daily YouTube Data Pull

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Set date variable
        id: vars
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: video_data_${{ steps.vars.outputs.DATE }}
          path: output/video_data*.csv
