name: Daily YouTube Data Pull

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10:00 UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Required for pushing back to the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Set date variable
        id: vars
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push CSV
        run: |
          git add output/*.csv
          git commit -m "Add daily video data - ${{ steps.vars.outputs.DATE }}" || echo "No changes to commit"
          git push
